Soft cell update
rosberry/CollectionViewTools pull request #22
Opened 2021-06-17 09:35 UTC by ntunin

- Implemented soft cell update collection view manager mode
- Improved logic for diff items comparison
- All factory examples placed under separate target

<p align = "center">
<img src="https://user-images.githubusercontent.com/15152385/122371162-796f4c00-cf81-11eb-8aa8-c2fc89c0811f.gif" width = 250>
</p>

2021-06-18 11:18 UTC, zhvrnkov requested changes

2021-06-18 11:18 UTC, zhvrnkov commented on Sources/CollectionViewManager.swift
> +    open func softUpdate(cellItemsAt indexes: [Int],
- softUpdate and replace have so much common 
- softUpdate as default CVM update

2021-07-12 05:57 UTC, stason314 approved these changes

2021-07-16 04:23 UTC, zhvrnkov approved these changes

2021-07-16 04:26 UTC, merged