Remove array traversal on each cellItem lookup
rosberry/CollectionViewTools pull request #3
Opened 2018-11-01 04:40 UTC by disabled

Provides a huge performance boost on collections with lots of elements.

2018-11-02 06:31 UTC, artemnovichkov approved these changes

2018-11-02 08:33 UTC, Antowkos requested changes

2018-11-02 08:33 UTC, Antowkos commented on Sources/CollectionViewManager.swift
> +        guard sectionItem.cellItems.count > indexPath.row else {
It would be better to combine all guards in one

2018-11-16 04:32 UTC, Antowkos approved these changes
It would be better to move every condition to a new line, but isn't necessary though

2018-11-16 06:07 UTC, evgenmikhaylov approved these changes

2018-11-16 06:34 UTC, merged