Add collection view as a parameter to size function
rosberry/CollectionViewTools pull request #8
Opened 2018-11-16 05:09 UTC by Antowkos

Fix for https://github.com/rosberry/CollectionViewTools/issues/7

2018-11-16 05:52 UTC, evgenmikhaylov requested changes

2018-11-16 05:52 UTC, medvedzzz commented on Sources/Protocols/CellItem/CollectionViewCellItem.swift
> +    func size(in collectionView: UICollectionView) -> CGSize
```suggestion
    func size(in collectionView: UICollectionView, sectionItem: CollectionViewSectionItem) -> CGSize
```

2018-11-16 06:00 UTC, evgenmikhaylov approved these changes

2018-11-16 06:37 UTC, artemnovichkov requested changes

2018-11-16 06:37 UTC, artemnovichkov commented on Sources/Protocols/CellItem/CollectionViewCellItem.swift
> +    func size(in collectionView: UICollectionView, sectionItem: CollectionViewSectionItem) -> CGSize
Why did you decide to remove the old function?

2018-12-07 07:42 UTC, ghost approved these changes

2018-12-14 09:48 UTC, artemnovichkov approved these changes

2018-12-14 09:49 UTC, merged